### ISSUE TITLE
create a new mountains polygon shapefile

### ISSUE THREAD

**Issue by jlblancopastor** [jlblancopastor/CCME#4]
Hola @Janopecuario, 
acabo de ver que el shapefile con la info de las montañas está incompleto.
He bajado los dos archivos disponibles: GMBA mountain inventory V1.o(entire world) y GMBA mountain inventory V1.0(Supplementary large-scale set)
Habría que combinar ambos archivos para crear nuestro shapefile. He puesto un comentario en el script
¿Podrías hacerlo tu?

**Comment by Janopecuario** [comment]
No me había enterado de esto, cosas del github. Ahora lo miro, estaba finiquitando biovars.

**Comment by Janopecuario** [comment]
Hola, igual lo tenemos que hablar.... la verdad es que no estoy seguro de qué es lo que falta!! En navidades fue cuando creé esas líneas y funcionaban tal cual...

**Comment by jlblancopastor** [comment]
Hola, simplemente que el shapefile de las montañas que ibamos a usar está incompleto.
Habría que unir los dos shapefiles que te puedes descargar de aquí
https://ilias.unibe.ch/goto_ilias3_unibe_cat_1000515.html

de hecho ya los he descargado aquí:
Google Drive\Climate Change in Mountain Ecosystems\Climate data\Qgis
Serían estos dos archivos: GMBA mountain inventory V1.o(entire world) y GMBA mountain inventory V1.0(Supplementary large-scale set)

En Qgis creo que tan solo sería hacer Vector/GeoprocessingTools/Union

**Comment by JavierFajado** [comment]
Ey!
Estaba mirando las capas, he encontrado lo que abajo os copio en un archivo de texto que viene con los datos. Es la descripción de las capas, esas de las que habla José Luis están en los puntos 1 y 3. Según entiendo, el shapefile en el punto 3 (el archivo "supplementary") es una delimitación más gruesa de los 17 principales sistemas montañosos. Creéis que lo mejor sería unir los dos archivos o buscar una forma de decidir entre el polígono "fino" (1) o en grueso (3) en función de cómo se distribuyan los puntos? Si los unimos, se nos puede generar el problema de que los puntos interseccionen con un polígono de cada cada, porque se superponen. Para algunos casos el perfil grueso de la montaña puede ir bien, pero para otros creo que puede quedar demasiado grande. Quizás se complica un poco, pero se me ocurre que podríamos buscar el perfil de montaña primero en el shapefile "fino", y si los puntos no entran en el polígono (porque tengan una distribución más amplia), buscar el "grueso".

"- The files required to work in a GIS software are organized in three folders: 
1) "GMBA mountain inventory_V1.0(entire world)" provides 1 set of GIS files (.dbf, .prj, .shp, .shx) showing the full world-wide inventory. The attribute table includes object name, country, and the online resource used for its identification (see below).  
2) "GMBA mountain inventory_V1.0(by mega-region)" provides 8 sets of GIS files (.dbf, .prj, .shp, .shx), one for each mega-region of the world (Africa, Asia, Australia, Europe, Greenland, North America, Oceania, and South America). Each of these sets of files shows an inventory for a specific mega-region and the attribute table includes object name, country, and the online resource used for its identification (see below). 
3) "GMBA mountain inventory_V1.0(supplementary large-scale set)" provides 1 set of GIS files (.dbf, .prj, .shp, .shx) showing an inventory of 17 large mountain systems of the world. Any of these 17 objects includes at least all the inventory entries listed in "GMBA mountain inventory_V1.0(entire world)" that are part of the specific mountain system but can include additional terrain that is not included in any specific inventory entry listed in "GMBA mountain inventory_V1.0(entire world)". The attribute table inclues object name and country"

**Comment by jlblancopastor** [comment]
Hola,
Ok, la solución de Javi me parece buena (si veis que es posible hacerlo)

**Comment by JavierFajado** [comment]
He estado mirando los puntos y cómo se superponen con las capas. 
Me parece que hay pocas especies con puntos que no caen dentro de los polígonos "finos". La mayoría son de África del este, donde los grandes lagos, y he visto otra de Nueva Zelanda (Xenicus gilviventris). Puede que haya alguna más... aunque son pocas las zonas donde el polígono "grueso" es más extenso que el "fino". De las africanas, si no me equivoco, me parece que están en una zona de meseta con algunas montañas altas, como el Kilimanjaro. Ahí veo que varias especies tienen puntos en la zona de meseta, no solo en las montañas. He visto que también pasa con algunas especies europeas, que están en las montañas pero, esporádicamente, tienen un punto en alguna zona más baja, pero en zonas donde ni siquiera el polígono "grueso" dibuja montañas.

**Comment by JavierFajado** [comment]
Me parece que sí va a ser necesario establecer un criterio para elegir entre uno de los polígonos o el otro. Tanto si unimos las 2 capas como si las utilizamos jerárquicamente (como yo decía, mirando primero el "fino" y, si es necesario, luego el "grueso"), vamos a tener puntos que intersecten con un polígono de montaña fino y, al mismo tiempo, con otro grueso, porque estos suelen superponerse. Otro problema es que el polígono más grueso normalmente es bastante extenso, y cuando tengamos que recurrir a él nos va a meter un trozo bastante grande. Lo último que estaba pensando es qué vamos a hacer con esos puntos que caen fuera de la montaña, por ejemplo, en Europa. Esos puntos los excluimos de los análisis o se van a extender las capas para incluirlos?

**Comment by jlblancopastor** [comment]
Hola,
Pues lo que yo haría es utilizar el "fino" cuando todos lo puntos caigan dentro de éste. Si algún punto cae fuera en pues utilizaría el "grueso". Es cierto que el polígono grueso a veces es muy extenso, pero aún así creo que es mejor criterio que establecer límites a ojo. Los puntos que caen fuera de la montaña no deberían utilizarse (no creo que haya muchos).

**Comment by Janopecuario** [comment]
Hola, había contestado como si fuera un correo esta tarde y no sé si habéis llegado a ver algo, pero yo estos últimos mensajes no los había visto. Estaba mirando también cómo superponen en ArcGIS y en realidad los que no están en los finos pero sí en los gordos son pocos. Lo que haría sería para esos, señalarlos de alguna manera como que se modela con otros límites porque no se cubren. En realidad me preocupan los que no caen ni en una ni en otra... ¿se ha hecho un control de calidad de la precisión de las coordenadas? Sería necesario revisar esos puntos en mi opinión antes de dar más pasos. Javi, ¿tú eres capaz de meter las órdenes en el script? Tal y como lo veo sería en un bucle con tres pasos... 1) ver si todos los puntos caen dentro de polígonos finos, si no, 2) comprobar si todos quedan abarcados entre los gruesos y los finos, y 3) si no se cumple esa condición, hay que decidir qué hacemos con esos. Yo no estoy ahora mismo muy por la labor de descartar puntos que en teoría tienen que ser especies alpinas pero que caen fuera del ámbito montañoso, sin saber antes qué pasa con esas coordenadas.

**Comment by jlblancopastor** [comment]
Hola,
Si, hay que contestar a los mails en GitHub, si no creo que no se reciben.
Yo hice una revisión de las especies, viendo el área de distribución y viendo donde caen los puntos para cada especie. Hay dos cuestiones: por un lado hay algunas especies con poblaciones "raras" fuera de su hábitat normal (montaña). Éste es por ejemplo el caso de el Pika americano (Ochotona princeps), creo que en este caso han muestreado poblaciones en invierno y las pikas pueden bajar en esa época del año. Realmente nos interesan las poblaciones de verano, ya que ésta es la época que es importante desde el punto de vista del cambio climático. Creo que en ese caso habría que eliminar las poblaciones "raras" en la modelización. La segunda cuestión es la delimitación de las montañas. La delimitación del GMBA es demasiado restrictiva en muchas ocasiones, en otras creo que simplemente se han equivocado. Por ejemplo, segun el GMBA no hay montaña en el Sistema Ibérico, cuando allí hay altitudes de más de 2000m en algunos picos. Ésto es un problema mayor que no tengo muy claro como solucionar. Quizás es un error que debemos asumir si damos por buena la delimitación del GMBA. De todas formas son pocas las poblaciones que tendrían este segundo problema. 

Tal y como lo veo yo hay dos opciones:
1) hacer la lista de órdenes que indica Jano y en el paso 3 eliminar en cualquier caso las poblaciones que caigan fuera de las montañas delimitadas por el GMBA
2) hacer la lista de órdenes que indica Jano, en el paso 3 (especies que caen fuera de las montañas) lo que podríamos hacer es delimitar un área teniendo en cuenta los puntos de presencia en lugar de usar el shapefile de las montañas del GMBA.

Que opinais?

**Comment by Janopecuario** [comment]
Ya veo...
Entonces entiendo que las poblaciones raras van a ser sobre todo animales...? No me mojaría de todas maneras por que la época más determinante sea siempre el verano. Seguramente sí, pero como digo, no me mojaría.
Yo no sé si en carpeta de QGis del google drive están todas las especies o no (Vladi ha dicho que faltaba algo) pero son pocas. El resto sirven los boundaries. Así que yo opto por la opción 2. En la línea 8 del código he puesto que se cree un marco de datos para luego poder señalar qué especies parten con boundaries artificiales a partir de su propia distribución.

**Comment by jlblancopastor** [comment]
Si, en la carpeta de QGis del google drive está el dataset final completo. Vladi dice que faltaba alguna? que yo sepa no falta ninguna, pero le podemos preguntar.
Ok, a la opción 2.

**Comment by JavierFajado** [comment]
Yo también creo que lo mejor sería usar la capa GMBA y considerar casos atípicos de forma particular. Voy a hacer lo que me pidió Jano, sacar cuáles son las especies y las presencias dentro de estas que no entran en los polígonos de montaña y os mando la tabla (perdonadme, lo estaba haciendo ayer antes de contestar pero surgió algo y lo dejé a medias y sin responder). Ahí podemos ver las especies con puntos "raros" y definir qué hacer. Una idea que se me ocurre podría ser hacer el búfer más pequeño que contenga todos los puntos a partir del polígono de la montaña.

**Comment by jlblancopastor** [comment]
Gracias Javi por encargarte,
La idea del búfer me parece genial

**Comment by JavierFajado** [comment]
A ver... que tengo un poco de lío y no sé cómo sugerir el cambio en el script directamente en Github... :S

Por un lado, he metido en el drive una tabla con las presencias de todas las especies y que tiene 2 nuevas columnas, fino y grueso, donde hay un 1 si el punto está contenido en esa capa de montañas o 0 si está fuera. Las especies con algún punto fuera de ambos son:
 [1] "Androsaceae vitaliana"     "Campanula alpina"         
 [3] "Cardamine nipponica"       "Edraianthus graminifolius"
 [5] "Ochotona princeps"         "Onobrychis transsilvanica"
 [7] "Oreamnos americanus"       "Pedicularis kansuensis"   
 [9] "Polylepis australis"       "Rhodiola dumulosa"        
[11] "Sibiraea angustata"        "Tetraogallus himalayensis"

En realidad, no sé si es mejor usar una tabla como ésta (o, sería equivalente, añadir estas 2 columnas en el shapefile de cada especie) o es mejor meter la comprobación en el mismo script.

Había pensado que podríamos meter en el script algo como lo siguiente, que primero mira si todas las presencias entran en los polígonos de las montañas y, si no, hace búfers a estos polígonos de 0.2 en 0.2º hasta que todas entren:

####

# Todas las presencias en shapefile?
if (nrow(shape.species) != nrow(shape.species[(shape.mountain[shape.mountain$Name %in% names.mountain,]),])) {
  all.occ.in.mountain <- FALSE
} else {all.occ.in.mountain <- TRUE}

# Shapefile de montañas a utilizar
my.mountain <- shape.mountain[shape.mountain$Name %in% names.mountain,]

# Si alguna presencia estaba fuera de montañas, ampliar polígonos con búfer
if (all.occ.in.mountain == FALSE){
  while(nrow(shape.species[my.mountain,]) != nrow(shape.species)){
    my.mountain <- gBuffer(my.mountain, byid=T, width=0.2)
  }
}

####

No obstante, eso está hecho sobre lo que había en el script, que creo que solo mira el shapefile fino. Habría que incorporar un paso intermedio que buscara en el grueso antes de hacer el búfer.
El problema es que creo que Jano no lo tiene organizado para sacar un shapefile en forma de objeto, sino extraer los poligonos directamente a la hora de cortar las variables a partir de los nombres de las montañas. De esa forma queda, desde luego, mucho "más elegante", pero no se me ocurría cómo incorporar lo del búfer... Jano, tú ves una forma o tendríamos que sacar un objeto como he puesto ahí?

Es que no controlo tanto el script como para atreverme a cambiarlo, y a Jano le queda todo mucho más compacto, jaja. No sé si ves bien meter algo parecido a eso que te mando?

**Comment by JavierFajado** [comment]
Vaya... había unas cosas comentadas (#) entre las líneas del código y las ha puesto en grande y en negrita... tengo que aprender Markdown, jaja

Si aún así queréis ver la tabla, la he puesto en Species Data con el nombre "Data_species_in_mountains.csv"

**Comment by jlblancopastor** [comment]
Genial Javi, vamos a esperar a ver que dice Jano.
Mi recomendación es que los códigos que mencionas los introduzcas haciendo pull request (para eso usamos github, jeje) y que Jano los acepte o los modifique como el vea conveniente. Admás creo que es mucho más facil ver todo el código en su conjunto

**Comment by JavierFajado** [comment]
Sí, tienes razón, jaja... no sé si lo he hecho bien.
No estaba seguro de si meterlo directo como un pull request porque está incompleto, y hace falta cambiar otras cosas que tiene Jano listas para que funciones. No quería meter la pata en el código cambiando muchas cosas...

**Comment by Janopecuario** [comment]
Hola! Ayer por la noche acepté el pull request sin muchos miramientos y sin mucho conocimiento de GitHub. Creo que está bien. He cambiado selected.shape.mountain por my.mountain tal y como avisaba Javi.

**Comment by jlblancopastor** [comment]
Genial chicos, parece que vamos dominando el GitHub!

**Comment by Janopecuario** [comment]
Bueno, creo que tengo que practicar ;-)
Por ejemplo, Javi, puedes ojear las líneas 52-58? Creo que funcionará bien la creación de un stack de biovariables, y de hecho en scripts sencillos lo hacía, pero siempre conviene revisar. Está escrito así para racanear líneas de código.

**Comment by JavierFajado** [comment]
A mi parece que esa parte está bien. Lo he probado con unos rasters y polígonos en mi ordenador y quedaban cortados como queremos. Bien!
Hombre, habrá que probar cuando esté listo... pero me da buena pinta.

PD: Perdón por lo de "my.mountain" lo puse rápido y sin pensarlo mucho... estaba mucho mejor lo que tú tenías antes, jajaja

**Comment by Janopecuario** [comment]
Pues se queda como "my.mountain" ;-)

**Comment by jlblancopastor** [comment]
Hola!,
Que tal va el script? has hecho ya una prueba @Janopecuario?
Podemos cerrar este Issue?

**Comment by Janopecuario** [comment]
Parece que sí que funciona, he añadido dos tablas que hay que generar para cada especie para tener los datos brutos de evaluación de los modelos y no ir a ciegas.

**Comment by jlblancopastor** [comment]
Genial, avísame si necesitas cualquier cosa de mi parte
